### ISSUE TITLE
BASIC word for user input

### ISSUE THREAD

**Issue by szczys** [Hack-a-Day/basic-badge#20]
Add a BASIC word that takes user input and assigns it to a variable.

Examples shown on this page:
[https://en.wikibooks.org/wiki/BASIC_Programming/Beginning_BASIC/User_Input](https://en.wikibooks.org/wiki/BASIC_Programming/Beginning_BASIC/User_Input)

**Comment by jaromir-sukuba** [comment]
Now, regarding the actual issue. In 0.70 I implemented simple input function returning user entered value, with parameter of string to be printed.
Program can look like this
```
5 rem user value repeater
10 let a = input "Enter value"
19 print "You entered: "
20 println a
```
(Notice that rem word is implemented too.) Now user is prompted "Enter value :" and program is stopped until user enters value and presses ENTER, Backspace works too.
Next two lines are probably obvious.

**Comment by szczys** [comment]
Tested and working.
