### ISSUE TITLE
Typing GOTO without line number locks badge

### ISSUE THREAD

**Issue by szczys** [Hack-a-Day/basic-badge#38]
* Type some lines with line numbers as normal
* Accidentally type "goto 10" without any line number
* Badge locks, cannot use BRK
* Badge must be reset and program buffer is lost

**Comment by jaromir-sukuba** [comment]
Yep, that's serious issue.
Since some words (like goto or for) shouldn't be available in interactive mode, I restricted availability of them in v 0.75, please try it.

**Comment by szczys** [comment]
Tested and working
