### ISSUE TITLE
Power On Self Test (POST)

### ISSUE THREAD

**Issue by szczys** [Hack-a-Day/basic-badge#4]
For successful manufacturing we need a way to test the hardware on the badge.

* Hold some button at power-up and POST will begin
* Screen test (fill with several different colors?)
* Print "testing speaker" on screen and play test tones
* Print "write to flash..." on screen and write to flash
* Read from flash, verify and print "Read from flash verified" (should write to this part of flash again with other data so future POST test doesn't get false positive)
* Some screen that represents all buttons on the badge and user presses every one to ensure they are all working properly
* What else?

**Comment by szczys** [comment]
I removed power button from testing keymap (as Voja suggested) and changed underscore to minus. BSP/DEL test working now.

Does this just leave flash chip test to finish out this feature? Will this be the CP/M drive format we were using from the menu?

**Comment by jaromir-sukuba** [comment]
FLASH is tested by reading ID, but I'll add CP/M format as last step in test.

**Comment by jaromir-sukuba** [comment]
I added one step for testing pins on GPIO header, just running high level among the IO pins. Connect LEDs and you have running light.
Also, there is last step allowing to format FLASH with CP/M filesystem.

**Comment by vantonic** [comment]
What do you think, should we put Volume Adjust under the Main Menu, which
is after Reset?

We could put a row, something like:

* Volume (Up and Down Arrow): 4 *

So when Up or Down arrows are pressed, the number changes in range 0...4.
Also a short BEEP (or a three-tone chord) with preset volume could be
played when arrow pressed. I think that the Volume setting should not be
initialized after Reset, but left as-is (inly trimmed in 0-4 range, like:
if VOLUME>4 then VOLUME=4).

**Comment by vantonic** [comment]
After a nearly critical delay from manufacturer, today I've finally got
PCBs for badges, I'll talk about details when we meet. I gave all
components and PCBs to the Pick'n'Place company immediatelly, and they will
finish it at Wednesday. After that we have to glue speakers and bezels,
probably in a few hours. (Bezels are laser cut today, I'll pick them
tomorrow).

So everything will be on time for programming and final testing, which
could be performed at Thursday and Friday.

This was damn close. Huh.

**Comment by vantonic** [comment]
I've noticed that RGB LEDs are not switched OFF in SLEEP mode. Please
switch them OFF, even better to store their state before going to sleep,
and then restore it after waking up.

**Comment by jaromir-sukuba** [comment]
Good catch, I fixed it, LED state is restored after wake-up.

**Comment by vantonic** [comment]
Yes, it works fine now.
Also, are we going to have a cursor in editor?

**Comment by szczys** [comment]
I think POST is complete so I'm closing this.
