### ISSUE TITLE
BASIC uin notworking

### ISSUE THREAD

**Issue by mastrogippo** [Hack-a-Day/basic-badge#41]
I'm sending stuff to the serial port.
In BASIC, if I use sload I can see the data I'm sending.
if I write

10 print uin 1
20 goto 10

nothing gets printed :(

**Comment by mastrogippo** [comment]
Note: UIN works only if there is nothing in the buffer. So you need to start sending data only afterrunning the BASIC program

**Comment by jaromir-sukuba** [comment]
uin parameter decides whether the function is blocking or not, see documentation. Anyway, the uin function seems fishy, will take a look at it.

**Comment by jaromir-sukuba** [comment]
I checked again the uin functon in both blocking and non-blocking mode, it seems to work.
Baudrate for badge is fixd to 19200, no handshake, 3,3V levels.
